# postgres:
#   host: localhost
#   db: oauth_server_db
#   user: postgres
#   pass: root
#   port: 5432

spring.config.activate.on-profile: postgres
spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth_server_db
    username: postgres
    password: root
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# spring:
#   jpa:
#     database: postgresql
#     database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#     open-in-view: false
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.PostgreSQL9Dialect
#     show-sql: false
#     generate-ddl: true
#     hibernate:
#       ddl-auto: update
#   datasource:
#     url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.db}
#     username: ${postgres.user}
#     password: ${postgres.pass}
#     driver-class-name: org.postgresql.Driver
#   sql:
#     init:
#       platform: postgres
#       mode: always